services:
  postgres-db:
    image: postgres:18.3
    container_name: medilabo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medilabo_patient
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot