spring.application.name=gateway
server.port=8090
logging.level.org.springframework.cloud.gateway=TRACE
################### LOCAL URLS ##########################
patient.api.url=http://localhost:8081
notes.api.url=http://localhost:8082
screening.api.url=http://localhost:8083