spring.application.name=screening
server.port=8083
logging.level.org.springframework=error
################### LOCAL URLS ##########################
patient.api.url=http://localhost:8090/api/patients
notes.api.url=http://localhost:8090/api/notes