spring.application.name=ui
server.port=8080
################### LOCAL URLS ##########################
patient.api.url=http://localhost:8090/api/patients
notes.api.url=http://localhost:8090/api/notes
screening.api.url=http://localhost:8090/api/screening